# Generated by Django 4.2.7 on 2025-01-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_campus_user_dept_code_user_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
