# Generated by Django 4.2.7 on 2023-11-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=500, null=True)),
                ('group_email', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='', verbose_name='/attachments')),
                ('dt_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PushNotificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
                ('dt_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('userid', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=1, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
