# Generated by Django 4.2.7 on 2025-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
