# Generated by Django 4.2.7 on 2025-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pushnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
