# Generated by Django 4.2.7 on 2025-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pushnotification_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='attachment_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
